### ISSUE TITLE
chef lvm cookbook now use chef-ruby-lvm library instead of di-ruby-lvm

### ISSUE THREAD

**Issue by Tcharl** [shortdudey123/chef-gluster#103]
I made a PR (#102) in order to have this cookbook now compliant with the [chef-lvm](https://github.com/chef-cookbooks/lvm) new lvm gem usable (see the according readme section).

Best regards,

**Comment by raviram203** [comment]
+1 
A neat cookbook. Hope you find @Tcharl pull request acceptable.

**Comment by shortdudey123** [comment]
Solved by #102
