### ISSUE TITLE
Current version of chef-gluster need peers specified by hostname

### ISSUE THREAD

**Issue by theundefined** [shortdudey123/chef-gluster#108]
I found, that current version of chef-gluster need peers specified by hostname. When hostnames and fqdns aren't globaly resolvable - sometimes is more usefull to use it by ip. Using gluster by ip's is also needed for example by kubernetes.

I made small PR(https://github.com/shortdudey123/chef-gluster/pull/107) to fix it - please include it :)
Works, and should not break anything.
I also replaced multiple || checks by one "[].include?(element)" - it's recomended way by rubocop.

**Comment by theundefined** [comment]
@shortdudey123  :-)

**Comment by shortdudey123** [comment]
Solved by #107
