### ISSUE TITLE
Supermarket

### ISSUE THREAD

**Issue by shortdudey123** [shortdudey123/chef-gluster#11]
Can you release this on the supermarket?  The gluster cookbook there isn't as extensible as this one

Existing one: https://supermarket.chef.io/cookbooks/gluster

**Comment by jared-k** [comment]
That would be ideal, and it's already been brought up: 
https://github.com/hw-cookbooks/gluster/issues/1

Our Gluster usage is shrinking though, so I'd like to transfer the repo to a new owner beforehand.

**Comment by shortdudey123** [comment]
:+1:

**Comment by shortdudey123** [comment]
Sounds like both you and @dmyers don't have much gluster usage anymore and don't want to maintain it.  Let me know if you would like me to take it over.

**Comment by jared-k** [comment]
@shortdudey123 If you're willing to take it over I'd be happy to hand this off to you. Confirm that I should transfer the repo to this username and I'll do that today.

**Comment by shortdudey123** [comment]
Sure, go for it!

**Comment by mikestephens** [comment]
@shortdudey123 sent you a request to take over the cookbook.

**Comment by shortdudey123** [comment]
@mikestephens thanks!

**Comment by shortdudey123** [comment]
@mikestephens - i added you and @jared-k as contributors so you guys can still add stuff if you would like :)

**Comment by mikestephens** [comment]
:+1:

**Comment by shortdudey123** [comment]
Finally uploaded this cookbook to the supermarket!
https://supermarket.chef.io/cookbooks/gluster
