### ISSUE TITLE
server_setup creates bogus nodes

### ISSUE THREAD

**Issue by jdblack** [shortdudey123/chef-gluster#15]
server_setup includes a call to Chef::Node.find_or_create.  This results in the creation of a bogus node if the FQDN of a node does not match the node name.  I have a potential fix, but have not yet submitted a pull request as I have not properly tested this branch yet.

    https://github.com/jdblack/chef-gluster/tree/dont_create_nodes

**Comment by jdblack** [comment]
*** Do not Merge Yet***

This is a work in progress. This branch intends to solve two problems:  This mostly works for me, but there is a bit of work to do involving races between the simultaneous provisioning of peer nodes.

I have continued this work in https://github.com/jdblack/chef-gluster/tree/gluster_based_on_nodenames 

The good news:
  1. Bogus peer nodes are no longer implicitly created.
  2.  Nodes are now referenced via attributes strictly by node name. The fqdn of peer nodes is looked up as necessary by the peer node.

The bad news:
  1. We need introduce some configurable delays to make this work robust against provisioning race conditions (e.g. bringing up nodes A and B at the same time). This patch, in its current state, should eventually converge, but who wants to wait?

**Comment by shortdudey123** [comment]
Fixed by https://github.com/shortdudey123/chef-gluster/commit/121994ae8c5c09884d295d765d683c2e916ae9cd
