### ISSUE TITLE
install gluster cli tools only

### ISSUE THREAD

**Issue by CBarraford** [shortdudey123/chef-gluster#20]
any suggestions on how to get chef to install the cli tools but not install gluster server and run the service??

**Comment by shortdudey123** [comment]
This what you are looking for? http://www.rpmfind.net/linux/RPM/centos/7.1.1503/x86_64/Packages/glusterfs-cli-3.6.0.29-2.el7.x86_64.html

if so, i can add a recipe that installs just that

**Comment by CBarraford** [comment]
i'm on ubuntu, but that looks like it installs the glusterfs cli tools. I was looking for `/usr/sbin/gluster`, but it seems i need to install the entire gluster server service. If thats the case, can i create a PR that uses an attr to enable/disables the daemon?
https://github.com/shortdudey123/chef-gluster/blob/master/recipes/server_install.rb#L32

**Comment by CBarraford** [comment]
My use case is this...

I have a gluster cluster, and a glusterfs client that is mounting the remote data. That client sometimes creates a directory, but then needs to set a quota for that directory. So i'm shelling out from that client to cli ... `/usr/sbin/gluster --remote-host=<GLUSTERHOST> volume <VOLUME> limit-usage <PATH>`.

So apparently i need to install gluster server on a gluster client, to be able to manage quotas remotely.

**Comment by shortdudey123** [comment]
Yeah looks like gluster-cli is only available in RPM form which is unfortunate.
