### ISSUE TITLE
Replacing a peer causes server_extend.rb to bomb

### ISSUE THREAD

**Issue by shortdudey123** [shortdudey123/chef-gluster#29]
If you remove a peer server along with the chef node and add a new host, the recipe will run `gluster volume add-brick` instead of `gluster volume replace-brick`.  This causes the chef-run to bomb out since the exit code from gluster is `1`.

**Comment by shortdudey123** [comment]
Replacing a brick on distributed-replicated
```
sudo gluster volume replace-brick chef old_hostname:/brick chef new_hostname:/brick commit force
```

**Comment by Seth-Karlo** [comment]
@shortdudey123 I'll try and find some time to look into this.

**Comment by shortdudey123** [comment]
@Seth-Karlo Cool! i was going to look at this today, but i will let you poke at it first since you wrote it :)
Thanks!!

**Comment by shortdudey123** [comment]
My thoughts were trying to find a peer that was disconnected and no longer a chef node.  Then using the new peer as the replacement.  It would only work if you had the same number of new peers as dead ones, otherwise you would not have a 1:1 replacement relationship and that could get interesting.

**Comment by Seth-Karlo** [comment]
@shortdudey123 No worries, I'd like to keep contributing to this! Feel free to tag me on anything you feel I could assist with. Sorry for the delay, I've had some critical operations failures this past week which have taken up my attention.

**Comment by shortdudey123** [comment]
Cool, thanks! :)
No problem on the delays, sounds like you had more important things to do haha

**Comment by Seth-Karlo** [comment]
Sorry I haven't updated anything recently, I've been struggling to come up with an effective way of getting this working without breaking it when bricks alone are added rather than peers being replaced (it's surprisingly difficult without knowing or storing previous state information). I'm still working on this in my spare time.

**Comment by shortdudey123** [comment]
No problem

My thoughts for a solution:
Run peer status to see if there is a peer disconnected, and if there is only 1 and only 1 new peer that isn't in the list, then do a replace.

Drawbacks:
if you are trying to add a peer while one is down, then it will get replaced instead of added if thats what you wanted.

**Comment by Seth-Karlo** [comment]
I have thought a lot about this and can't find an effective way to do this. The best solution is to extend first, then delete the old ones afterwards. I don't want to implement a one-to-one replacement only thing. The only other thought I had was to store in the volume a backup of the hosts as attributes, then we could check if that had changed with the 'new' peers. What do you think?

**Comment by shortdudey123** [comment]
That won't work in all cases.

Example:
a 2x2 cluster distributed replicated cluster, if 1 host dies, you can't add one, you have to add 2 since the total server count has to be a multiple of 2

**Comment by Seth-Karlo** [comment]
Ah yes, good point. Any suggestions on how to fix this? What do you think of the backup idea?

**Comment by shortdudey123** [comment]
Solved by https://github.com/shortdudey123/chef-gluster/pull/47
