### ISSUE TITLE
Peer brick listing always uses fqdn of peers

### ISSUE THREAD

**Issue by paustin01** [shortdudey123/chef-gluster#45]
My chef node names don't include the domain name (e.g. node.name is "server1"), so in node attributes I specify the gluster peer names to match so that the chef node lookup of peers works correctly.  However these chef nodes do also have an fqdn node attribute set (e.g. node.fqdn == "server1.example.net")  When compiling the list of bricks it's currently relying on the "chef_fqdn" variable which is defined as:

```
chef_fqdn = chef_node['fqdn'] || chef_node['hostname']
```

Which in my case will specify the brick names as "server1.example.net:/gluster/xvdf1/myvolume" and later when it executes `gluster volume create...` command it will bomb with

```
volume create: dataroot: failed: Host aze-tept-dat02.tresearch.net is not in 'Peer in Cluster' state
```

**Comment by shortdudey123** [comment]
Solved by https://github.com/shortdudey123/chef-gluster/pull/47
