### ISSUE TITLE
requier 'lvm' error

### ISSUE THREAD

**Issue by skircr** [shortdudey123/chef-gluster#64]
I am getting following error when trying to build new gluster replica. Cookbook was installed using berks.  Any recommendations for fixing this?

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/gluster/recipes/volume_extend.rb:

 18:  # limitations under the License.
 19:  #
 20:  node['gluster']['server']['volumes'].each do |volume_name, volume_values|
 21:    # 1. Get the current size of the logical volume
 22:    # 2. Compare to the size set for the gluster volume
 23:    # 3. If different, run a resize action against that volume
 24:    # ToDO: change hardcoded VG name gluster into an attribute
 25>>   require 'lvm'
 26:
 27:    LVM::LVM.new do |lvm|
 28:      lvm.logical_volumes.each do |lv|
 29:        # I'm ignoring these as I think this layout helps readability
 30:        # rubocop:disable Style/Next, Style/CaseIndentation, Lint/EndAlignment
 31:        if lv.full_name.to_s == "gluster/#{volume_name}"
 32:          lv_size_cur = lv.size.to_i
 33:          # Borrowed from the lvm cookbook
 34:          volume_lv_size_req = case volume_values['size']

**Comment by shortdudey123** [comment]
What version or commit hash of the cookbook are you using?

**Comment by skircr** [comment]
Gluster Cookbook 5.0.1
LVM Cookbook downloaded via berks 2.1.2

**Comment by shortdudey123** [comment]
Try the master branch for gluster and make sure that works

**Comment by skircr** [comment]
Downloaded master brunch and that woked! Thanks!

Was that a problem with a version stored in supermarket or did berks download brake it?

**Comment by shortdudey123** [comment]
Fix just hasn't been pushed up to supermarket yet :)

**Comment by shortdudey123** [comment]
@skircr just released master to supermarket which includes the fix you are looking for `5.0.2`
