### ISSUE TITLE
Incorrect case statement in providers/mount.rb

### ISSUE THREAD

**Issue by vchung-nz** [shortdudey123/chef-gluster#70]
The mount provider will never use backupvolfile-server during mount because the case statement is not correct:

```
def mount_options_for_backup_server
  case new_resource.backup_server.class  # will not === match either when statement
  when String
    ',backupvolfile-server=' + new_resource.backup_server
  when Array
    ',backupvolfile-server=' + new_resource.backup_server.join(',backupvolfile-server=')
  end
end
```
Code: https://github.com/shortdudey123/chef-gluster/blob/master/providers/mount.rb#L84

**Comment by shortdudey123** [comment]
What version of the cookbook are you using?

Integration tests show this is working correctly
```
         File "/etc/fstab"
           should be file
           content
             should match /^gluster2:\/gv0 \/mnt\/gv0 glusterfs defaults,_netdev,backupvolfile-server=gluster1 0 0$/
```

**Comment by vchung-nz** [comment]
I am using 5.0.2 as well.

I am not sure why the current code passed testing but it should not have worked because of how the "===" method is evaluated for class.  Please search for "ruby class in case statement" in your favourite search engine for detail.

**Comment by shortdudey123** [comment]
What are you putting in for `backup_server`? and what does `/etc/fstab` show?

**Comment by vchung-nz** [comment]
I have tried both
```
    backup_server "backup1"
    backup_server ["backup1", "backup2"]
```
With either case, I always ended with just the default mount_option:  "defaults,_netdev". So to debug this behaviour I added a fallback else statement to mount.rb

```
def mount_options_for_backup_server
  case new_resource.backup_server.class
  when String
    ',backupvolfile-server=' + new_resource.backup_server
  when Array
    ',backupvolfile-server=' + new_resource.backup_server.join(',backupvolfile-server=')
  else
    Chef::Log.info "backup_server has unknown class? [" + new_resource.backup_server.class.name + "]"
  end
```
The case statement always fell through, even thought the class is shown correctly as "String" or "Array" in the log output.  After further research I found that the object itself should be in the case statement, not object.class, eg

```
def mount_options_for_backup_server
  case new_resource.backup_server
  when String
```
It works for me once I made this change.

**Comment by shortdudey123** [comment]
Hmm i see what you mean with respect to classes in case statements on http://blog.honeybadger.io/rubys-case-statement-advanced-techniques/
However, if thats true, then integration tests should be failing
